// <auto-generated />
namespace YandS.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedClosureDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedClosureDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202308021145477_AddedClosureDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
