// <auto-generated />
namespace YandS.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedSessionFollowLawyerColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedSessionFollowLawyerColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202307170107376_addedSessionFollowLawyerColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
